Include LICENSE in compiled jar
mixer/beam-client-java pull request #61
Opened 2017-05-19 18:14 UTC by pahimar

Also added a licenses block to the pom

2017-05-19 18:21 UTC, connor4312 requested changes

2017-05-19 18:21 UTC, connor4312 commented on pom.xml
> +            <url>https://opensource.org/licenses/mit-license.php</url>
Need copyright holder / date?

2017-05-19 18:21 UTC, connor4312 commented on src/main/resources/LICENSE
> +Copyright (c) 2016 Beam Interactive, Inc.
Should read `Copyright (c) Microsoft`

2017-05-19 18:25 UTC, pahimar commented on pom.xml
> +            <url>https://opensource.org/licenses/mit-license.php</url>
Examples I've seen have shown that for the licenses block, they point to the central definition of the license. The included license in the repo is considered the master license for the project. We do not need the licenses stanza to be compliant, however - it's just extra.

Do we have a central posted license, outside of our repos, that we can link to?

2017-05-19 18:31 UTC, pahimar commented on src/main/resources/LICENSE
> +Copyright (c) 2016 Beam Interactive, Inc.
Fixed

2017-05-19 18:55 UTC, connor4312 commented on pom.xml
> +            <url>https://opensource.org/licenses/mit-license.php</url>
Let me PM CELA

2017-05-24 13:38 UTC, connor4312 approved these changes

2017-05-24 14:56 UTC, merged